"""Stand-in for Path 2 while its harness produces no output in this checkout.

Path 2 (``origin/path2-remediation``) is a real agent-driven remediation
harness, but it writes its patches to a git-ignored ``remediation/out/`` that
does not exist here, and it cannot run on this machine (branch not checked out,
its vendored OpenClaw not installed, no local model pulled).  So the patch
*content* below is generated by a deterministic rule, not by an agent.

What this module deliberately does **not** fake:

* the violation it patches is the real one Path 1 just reported;
* the patch is applied to a real copy of the real source file;
* whether it worked is decided by really re-running Path 1 over the patched
  copy, not by a hardcoded ``verified: True``.

Its output is shaped exactly like a Path 2 ``out/<id>/report.json`` (including
the ``mongo_patch`` record) so the real Path 2 bridge can consume it unchanged.
``model_used`` names this module, so nothing downstream can mistake a stand-in
patch for an agent-authored one.
"""

from __future__ import annotations

import difflib
import re
from collections.abc import Mapping
from typing import Any

MODEL_USED = "simulated:pipeline.patch_stub (no Path 2 output available)"

SUPPORTED_RULES = ("button-name",)


class UnsupportedViolation(RuntimeError):
    """Raised when the stand-in has no deterministic fix for a rule."""


def _selector_token(selector: str) -> tuple[str, str]:
    """Split a simple ``.class``/``#id`` selector into (kind, name)."""
    last = selector.strip().split()[-1] if selector.strip() else ""
    if last.startswith("."):
        return "class", last[1:]
    if last.startswith("#"):
        return "id", last[1:]
    return "tag", last


def _accessible_name_from_selector(selector: str) -> str:
    """Derive a human label from the element's own selector.

    Nothing about the page is hardcoded: the label comes from the selector the
    scanner reported, with a trailing button/btn/icon word dropped.
    """
    _, name = _selector_token(selector)
    words = [w for w in re.split(r"[-_]+", name) if w]
    while len(words) > 1 and words[-1].lower() in ("button", "btn", "icon", "control"):
        words.pop()
    return " ".join(words).strip().capitalize() or "Button"


def _find_element_line(lines: list[str], selector: str) -> int:
    kind, name = _selector_token(selector)
    if kind == "class":
        pattern = re.compile(r'class="[^"]*\b' + re.escape(name) + r'\b[^"]*"')
    elif kind == "id":
        pattern = re.compile(r'id="' + re.escape(name) + r'"')
    else:
        pattern = re.compile(r"<" + re.escape(name) + r"[\s>]")
    for index, line in enumerate(lines):
        if pattern.search(line):
            return index
    raise UnsupportedViolation(f"selector {selector!r} not found in source file")


def _add_aria_label(line: str, selector: str, label: str) -> str:
    """Insert an aria-label into the opening tag that carries the selector."""
    kind, name = _selector_token(selector)
    if kind == "class":
        needle = re.compile(r'class="[^"]*\b' + re.escape(name) + r'\b[^"]*"')
    elif kind == "id":
        needle = re.compile(r'id="' + re.escape(name) + r'"')
    else:
        needle = re.compile(r"<" + re.escape(name) + r"\b")
    match = needle.search(line)
    if not match:
        raise UnsupportedViolation("could not locate the attribute anchor to patch")
    if 'aria-label="' in line[match.start() : match.start() + 400]:
        raise UnsupportedViolation("element already has an aria-label")
    insert_at = match.end()
    return line[:insert_at] + f' aria-label="{label}"' + line[insert_at:]


def build_patch(violation: Mapping[str, Any], source_text: str) -> dict[str, Any]:
    """Return the snippets and unified diff that fix ``violation``.

    Raises ``UnsupportedViolation`` rather than inventing a patch it cannot
    justify, so an unhandled rule fails the pipeline loudly.
    """
    rule_id = violation.get("rule_id")
    if rule_id not in SUPPORTED_RULES:
        raise UnsupportedViolation(
            f"the stand-in only fixes {', '.join(SUPPORTED_RULES)}; got {rule_id!r}"
        )
    selector = violation.get("selector") or ""
    source_file = violation.get("source_file") or "unknown"

    lines = source_text.splitlines(keepends=True)
    index = _find_element_line(lines, selector)
    original_line = lines[index]
    label = _accessible_name_from_selector(selector)
    patched_line = _add_aria_label(original_line, selector, label)

    patched_lines = list(lines)
    patched_lines[index] = patched_line
    patched_text = "".join(patched_lines)

    diff = "".join(
        difflib.unified_diff(
            lines,
            patched_lines,
            fromfile=f"a/{source_file}",
            tofile=f"b/{source_file}",
            n=3,
        )
    )
    return {
        "rule_id": rule_id,
        "selector": selector,
        "source_file": source_file,
        "line": index + 1,
        "accessible_name": label,
        "original_snippet": original_line.strip(),
        "patched_snippet": patched_line.strip(),
        "patched_text": patched_text,
        "patch_diff": diff,
        "model_used": MODEL_USED,
    }
